---
kind: pipeline
type: docker
name: object-storage-ui

platform:
  os: linux
  arch: amd64

steps:
- name: build-push-image
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  settings:
    platform: linux/amd64
    build_args:
      - SHA=${DRONE_COMMIT_SHA:0:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: robbymilo/object-storage-ui
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - latest

trigger:
  event:
  - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock