---
kind: pipeline
type: docker
name: object-storage-ui

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golang:1.21.4-alpine
  commands:
    - apk add make git curl
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
    - make lint

- name: build-push-image
  image: plugins/docker
  environment:
    DOCKER_BUILDKIT: 1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  settings:
    platform: linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: robbymilo/object-storage-ui
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - latest
  depends_on:
    - lint

trigger:
  event:
  - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock