---
kind: pipeline
type: docker
name: object-storage-ui

platform:
  os: linux
  arch: amd64

steps:
- name: build-container
  image: plugins/docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker build . -t robbymilo/object-storage-ui-build-container:latest

- name: build
  image: robbymilo/object-storage-ui-build-container:latest
  pull: if-not-exists
  commands:
  - make all

trigger:
  event:
  - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock